<?php

namespace Troiswa\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function findArticlesbyCategory($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TroiswaBlogBundle:Article a Join a.category c WHERE c.id = :id')
            ->setParameter('id', $id)
            ->getResult();
    }
}
